
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS AUTHOR BEGIN DOC END ITEM ITEMIZE LB RB SECTION SUBSECTION TEXT TITLEdoc : BEGIN LB DOC RB content END LB DOC RBcontent : title author abs sections subsections itemize TEXTtitle : TITLE LB TEXT RBauthor : AUTHOR LB TEXT RBabs : BEGIN LB ABS RB TEXT END LB ABS RBsections : sections section\n                | sectionsection : SECTION LB TEXT RB TEXTsubsections : subsections subsection\n                    | subsectionsubsection : SUBSECTION LB TEXT RB TEXTitemize : BEGIN LB ITEMIZE RB items END LB ITEMIZE RBitems : items item\n              | itemitem : ITEM TEXT'
    
_lr_action_items = {'BEGIN':([0,10,27,28,31,37,50,],[1,14,35,-10,-4,-9,-11,]),'LB':([1,6,11,12,14,20,30,35,44,58,],[3,9,16,17,19,26,38,41,48,59,]),'TITLE':([5,],[6,]),'DOC':([3,17,],[4,24,]),'SECTION':([15,21,22,29,45,55,],[20,20,-7,-6,-8,-5,]),'AUTHOR':([7,18,],[11,-3,]),'ITEM':([49,53,54,56,57,],[52,52,-14,-15,-13,]),'ABS':([19,48,],[25,51,]),'SUBSECTION':([21,22,27,28,29,37,45,50,],[30,-7,30,-10,-6,-9,-8,-11,]),'RB':([4,13,23,24,25,34,43,46,51,60,],[5,18,31,32,33,40,47,49,55,61,]),'TEXT':([9,16,26,33,36,38,40,47,52,61,],[13,23,34,39,42,43,45,50,56,-12,]),'END':([8,39,42,53,54,56,57,],[12,44,-2,58,-14,-15,-13,]),'ITEMIZE':([41,59,],[46,60,]),'$end':([2,32,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'subsections':([21,],[27,]),'author':([7,],[10,]),'doc':([0,],[2,]),'section':([15,21,],[22,29,]),'title':([5,],[7,]),'content':([5,],[8,]),'item':([49,53,],[54,57,]),'abs':([10,],[15,]),'subsection':([21,27,],[28,37,]),'items':([49,],[53,]),'sections':([15,],[21,]),'itemize':([27,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doc","S'",1,None,None,None),
  ('doc -> BEGIN LB DOC RB content END LB DOC RB','doc',9,'p_doc','latex_parse.py',82),
  ('content -> title author abs sections subsections itemize TEXT','content',7,'p_content','latex_parse.py',88),
  ('title -> TITLE LB TEXT RB','title',4,'p_title','latex_parse.py',101),
  ('author -> AUTHOR LB TEXT RB','author',4,'p_author','latex_parse.py',107),
  ('abs -> BEGIN LB ABS RB TEXT END LB ABS RB','abs',9,'p_abs','latex_parse.py',113),
  ('sections -> sections section','sections',2,'p_sections','latex_parse.py',119),
  ('sections -> section','sections',1,'p_sections','latex_parse.py',120),
  ('section -> SECTION LB TEXT RB TEXT','section',5,'p_section','latex_parse.py',130),
  ('subsections -> subsections subsection','subsections',2,'p_subsections','latex_parse.py',136),
  ('subsections -> subsection','subsections',1,'p_subsections','latex_parse.py',137),
  ('subsection -> SUBSECTION LB TEXT RB TEXT','subsection',5,'p_subsection','latex_parse.py',147),
  ('itemize -> BEGIN LB ITEMIZE RB items END LB ITEMIZE RB','itemize',9,'p_itemize','latex_parse.py',152),
  ('items -> items item','items',2,'p_items','latex_parse.py',157),
  ('items -> item','items',1,'p_items','latex_parse.py',158),
  ('item -> ITEM TEXT','item',2,'p_item','latex_parse.py',168),
]
